[package]
name = "desktop"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.15", features = [] }
tonic-build = "0.11"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta.19", features = [ "macos-private-api", "protocol-asset"] }
# tauri_plugin_jarvis = { path = "../../../packages/tauri_plugin_jarvis" }
tauri-plugin-clipboard = { path = "../../../vendors/tauri-plugin-clipboard" }
tauri-plugin-store = "2.0.0-beta.6"
applications = { path = "../../../vendors/applications-rs" }
tauri-plugin-dialog = "2.0.0-beta.7"
tauri-plugin-shell = "2.0.0-beta.5"
tauri-plugin-upload = "2.0.0-beta.5"
tauri-plugin-notification = "2.0.0-beta.5"
tauri-plugin-log = "2.0.0-beta.4"
tauri-plugin-fs = "2.0.0-beta.7"
tauri-plugin-os = "2.0.0-beta.4"
tonic = "0.11"
prost = "0.12"
axum = { version = "0.6.20" }
axum-extra = { version = "0.8.0" }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tonic-reflection = "0.11.0"
rdev = "0.5.3"
serde_derive = "1.0.202"
anyhow = "1.0.86"
http = "1.1.0"
mime = "0.3.17"
tauri-icns = "0.1.0"
window-vibrancy = "0.5.0"
urlencoding = "2.1.3"


[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-global-shortcut = "2.0.0-beta.4"
tauri-plugin-updater = "2.0.0-beta.5"
