[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5.2", features = [ "protocol-all", "app-all", "macos-private-api", "updater",
    "path-all",
    "shell-all",
    "notification-all",
    "fs-all",
    "dialog-all",
    "window-all",
] }
applications = { path = "../../../vendors/applications-rs" }
awc = "3.4.0"
axum-extra = "0.9.3"
axum = "0.7.5"
tower = { version = "0.4.13", features = ["util"] }
tower-http = { "version" = "0.5.2", features = ["fs", "trace"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
tokio = "1.37.0"
tauri-plugin-clipboard = "0.6.9"
tauri_plugin_jarvis = { path = "../../../packages/tauri_plugin_jarvis" }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
window-vibrancy = "0.3.2"
sublime_fuzzy = "0.7.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
